### PR TITLE
[ TID-57 ]Feature/2fa authenticator app

### PR DESCRIPTION
**Pull request by MrFacundo**
Features / to test:

- Added an authenticator app method
- Refactored 2FA related code on back and front end
- Created or refactored existing 2FA endpoints
- Added comments

image

---------------------

### Two-Factor Authentication Enhancements:
* Removed `TwoFactorAuthenticationMixin` and `OTPToken` class from `two_factor_auth_mixin.py` and `otp_token.py` respectively, and refactored the 2FA logic into new views (`TwoFactorAuthView`, `AuthenticatorSetupView`, `VerifyAuthenticatorSetupView`, `VerifyOTPView`). [[1]](diffhunk://#diff-7c5f9bc2e4d14206fa6a9e47450f4e2ca53384daf83eae76d973888cc6e76950L1-L66) [[2]](diffhunk://#diff-5cd4279c748b8043b2af59e60d51d0adddfa2524fddc200c1003ef5bda03324cL1-L24) [[3]](diffhunk://#diff-fa39e5e45926c55c2165377e1057ac98b04407d336c4810785eb8464368fe99fL28-R58) [[4]](diffhunk://#diff-4dfa69966060ae83b410db54b1f0561678942be404b0e07e37d64328de6042c3L1-R129)
* Added methods to generate and validate OTPs, and to handle the setup and verification of the authenticator app.

### URL and View Updates:
* Updated `urls.py` to include new endpoints for setting up and verifying the authenticator app. [[1]](diffhunk://#diff-5df129349fd1329ba4d60780a35b3da68bfd38819e97d12d754563a9b1bf44bcL16-R20) [[2]](diffhunk://#diff-5df129349fd1329ba4d60780a35b3da68bfd38819e97d12d754563a9b1bf44bcL41-R47)
* Refactored `LoginView` to use `TwoFactorAuthView` and handle OTP generation and verification.

### User Model and Migrations:
* Updated the `CustomUser` model to include fields for storing the authenticator secret and validation secret.
* Added new migrations to support the changes in the user model. [[1]](diffhunk://#diff-eb369c3ba24dacd044dc5c441c873ccd1f64c52d833d0bd20bb3465ca4cf9bd7R1-R28) [[2]](diffhunk://#diff-598949ba9d78ee54b0992e0f1efa08464a6a9f945e48f9d58313af1e0e4be621R1-R18) [[3]](diffhunk://#diff-b972fee3a6df380ef3a61016f287d787ddb075d5a9d02b79acd201449f4bd78bR1-R21)

### Miscellaneous Changes:
* Added the `qrcode` library to `requirements.txt` for generating QR codes for the authenticator app setup.
* Added validation to prevent setting the authenticator 2FA method through the user serializer.

These changes enhance the security and flexibility of the 2FA system by introducing support for authenticator apps and improving the overall structure and maintainability of the code.

### CODE REVIEW

**Review by joaodibba — COMMENTED** [review]
User Creation:
I couldn’t create a user through the UI—it only worked via manage.py. I know this PR isn’t directly about user creation, but it’s worth flagging since it makes testing harder. Could you check if this is related or follow up on it?

2FA Issues:
The 2FA doesn’t seem to be working properly:

The OTP isn’t refreshing, which means it’s not secure or fully functional right now.
It also doesn’t seem like the 2FA flow is actually completing as expected.

**Review by heldergoncalves0 — DISMISSED** [review]
2FA doesn't work

**Comment by MrFacundo** [comment]
Let’s be precise about bugs and issues so we can fix them. Please point out exactly where the flow isn’t working or, if the issue is found in the code, point to the specific part that’s causing trouble.

I realize I didn’t explain how the register/2FA flow is supposed to work, so it's my bad it couldn’t be tested properly.

Manual user creation flow:
- It is being done via email verification. Env variables for email sending need to be set. Create a user using the UI and this should happen:

```
// create user and receive email
transcendence_back   | User with ID 11 registered successfully
transcendence_back   | Verification email sent to user ID 11
transcendence_back   | HTTP POST /api/user 201 [2.14, 172.18.0.1:52970]

// visit email verification link
transcendence_back   | HTTP OPTIONS /api/verify-email/11:IW22yberfditz1frzX8zs1gVa-3JKYWMk_f-Yb_SURc/ 200 [0.00, 172.18.0.1:60556]
transcendence_back   | HTTP GET /api/verify-email/11:IW22yberfditz1frzX8zs1gVa-3JKYWMk_f-Yb_SURc/ 200 [0.03, 172.18.0.1:60556]

// Login
transcendence_back   | HTTP POST /api/token/ 200 [0.18, 172.18.0.1:55250]
transcendence_back   | HTTP GET /api/user 200 [0.06, 172.18.0.1:55250]

```


2FA flow:

**Email**: use the UI to change settings and log in with 2FA. **Email is not being sent, OTP is only printed by the back end** . This should happen:
```
//update settings
transcendence_back   | HTTP PATCH /api/user 200 [0.02, 172.18.0.1:56056]  
transcendence_back   | HTTP GET /api/user 200 [0.04, 172.18.0.1:56056]

//Logout, login and get OTP
transcendence_back   | Generated OTP for ftroitero@gmail.com: 160404 // use this OTP
transcendence_back   | HTTP POST /api/token/ 200 [0.20, 172.18.0.1:56056]
transcendence_back   | HTTP OPTIONS /api/2fa/verify-otp/ 200 [0.00, 172.18.0.1:56056]

//Test a wrong OTP
transcendence_back   | Unauthorized: /api/2fa/verify-otp/
transcendence_back   | HTTP POST /api/2fa/verify-otp/ 401 [0.02, 172.18.0.1:56056] // unauthorized

//Test the current OTP
transcendence_back   | HTTP POST /api/2fa/verify-otp/ 200 [0.02, 172.18.0.1:56056] // 200 ok
```


**Auth App**: use the UI to change settings and log in with 2FA. Use the QR code with any authenticator app and input the OTP created by the app to confirm the setting. Log out and in with the app provided by the OTP.

```
// Get QR code
transcendence_back   | HTTP OPTIONS /api/2fa/setup/ 200 [0.00, 172.18.0.1:36474]
transcendence_back   | HTTP GET /api/2fa/setup/ 200 [0.04, 172.18.0.1:36474]

// Input the OTP provided by the app to confirm setting
transcendence_back   | HTTP OPTIONS /api/2fa/verify-setup/ 200 [0.00, 172.18.0.1:36474]
transcendence_back   | HTTP POST /api/2fa/verify-setup/ 200 [0.03, 172.18.0.1:36474]

// Logout and in, use the OTP provided by the app to confirm setting
transcendence_back   | HTTP POST /api/token/ 200 [0.21, 172.18.0.1:36474]
transcendence_back   | HTTP POST /api/2fa/verify-otp/ 200 [0.02, 172.18.0.1:36474]
transcendence_back   | HTTP GET /api/user 200 [0.03, 172.18.0.1:36474]
```

**Comment by heldergoncalves0** [comment]
I wanted to share my feedback from reviewing this PR. Just to clarify, I didn’t leave a comment on the last review because I went through it alongside João, and the issues we found were the same.

For this one, I noticed a couple of things while testing:

    Email 2FA Issue: When I try to log in with email-based 2FA active, I’m not receiving the code in my email.
    Authenticator App 2FA Issue: When I try to activate the app-based 2FA and input the OTP code, it doesn’t seem to work.

**Comment by MrFacundo** [comment]
Thanks for sharing @heldergoncalves0 

As I mentioned before, email isn’t being sent for Email 2FA right now to simplify development. An OTP is printed instead and that's what should be tested.

`Authenticator App 2FA Issue: When I try to activate app-based 2FA and enter the OTP code, it doesn’t seem to work.`

If you can, explain exactly what’s happening so we can debug the issue.

**Comment by MrFacundo** [comment]
Merging, if bugs, fix branches to be opened

**Pull request merged**
